version: '2.1'

services:
  # App
  common-app:
    build: ./
    command: yarn dev
    #env_file: .env.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app/api-graphql

    ports:
      - "3000:3000"

  realworld-graphql:
    extends: common-app

  realworld-graphql-prod:
    extends: common-app
    build:
      context: ./
      dockerfile: Dockerfile.production
    command: yarn start

